package hospital.management;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashMap;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


public class EmployeePanel extends javax.swing.JFrame {

    Connection con;
    public EmployeePanel(HashMap<String, String> userData) {
        initComponents();
        String db = "jdbc:mysql://localhost/hospital";
        String user = "root";
        String pass = "";
        
        try {
            con = DriverManager.getConnection(db, user, pass);
        }
        catch(Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
        String username = userData.get("username");
        namelabel.setText(username);
        appointmentpanel.setVisible(false);
        billpanel.setVisible(false);
        transactionpanel.setVisible(false);
        loadAppointmentsFromDatabase();
    }
    
    public EmployeePanel() {
        initComponents();
        appointmentpanel.setVisible(false);
        billpanel.setVisible(false);
        transactionpanel.setVisible(false);
    }
    
    //load all appointments from database into the table
    public void loadAppointmentsFromDatabase() {
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No database connection!", 
                                        "Database Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String query = "SELECT id, user, type, date, time FROM appointments";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            // Create list to store data
            List<Object[]> dataList = new ArrayList<>();

            while (rs.next()) {
                Object[] row = {
                    rs.getString("id"),
                    rs.getString("user"),
                    rs.getString("type"),
                    rs.getString("date"),
                    rs.getString("time")
                };
                dataList.add(row);
            }

            // Convert list to array and load into table
            Object[][] data = dataList.toArray(new Object[0][]);
            appointmentTable1.loadDataFromDatabase(data);

            rs.close();
            pst.close();

        } catch (SQLException ex) {
            System.out.println("Error loading appointments: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error loading appointments: " + ex.getMessage(), 
                                        "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradient32 = new hospital.management.Gradient3();
        sidepanel = new javax.swing.JPanel();
        gradient33 = new hospital.management.Gradient3();
        homeside = new javax.swing.JPanel();
        gradient34 = new hospital.management.Gradient3();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        appointmentside = new javax.swing.JPanel();
        gradient35 = new hospital.management.Gradient3();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        billside = new javax.swing.JPanel();
        gradient36 = new hospital.management.Gradient3();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        transactionside = new javax.swing.JPanel();
        gradient37 = new hospital.management.Gradient3();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        appointmentpanel = new javax.swing.JPanel();
        gradient31 = new hospital.management.Gradient3();
        hospitalSuccessButton1 = new hospital.management.HospitalSuccessButton();
        hospitalEmergencyButton1 = new hospital.management.HospitalEmergencyButton();
        hospitalPrimaryButton1 = new hospital.management.HospitalPrimaryButton();
        appointmentTable1 = new hospital.management.AppointmentTable();
        billpanel = new javax.swing.JPanel();
        gradient38 = new hospital.management.Gradient3();
        transactionpanel = new javax.swing.JPanel();
        gradient39 = new hospital.management.Gradient3();
        namelabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelappointment = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labeltransactions = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelbill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(860, 480));
        setMinimumSize(new java.awt.Dimension(860, 480));
        setResizable(false);

        gradient32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeside.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeside.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homesideMouseClicked(evt);
            }
        });
        homeside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("HOME");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gradient34.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        gradient34.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));
        gradient34.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        homeside.add(gradient34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 220, 480));

        gradient33.add(homeside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 40));

        appointmentside.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        appointmentside.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentsideMouseClicked(evt);
            }
        });
        appointmentside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("APPOINTMENTS");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        gradient35.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 160, -1, -1));
        gradient35.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, -1));

        appointmentside.add(gradient35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, 220, 480));

        gradient33.add(appointmentside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 40));

        billside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gradient36.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(44, 62, 80));
        jLabel3.setText("BILLS");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        gradient36.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 200, -1, -1));

        billside.add(gradient36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -190, 220, 480));

        gradient33.add(billside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 40));

        transactionside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("TRANSACTIONS");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gradient37.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 240, -1, -1));
        gradient37.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, -1));

        transactionside.add(gradient37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -230, 220, 480));

        gradient33.add(transactionside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 40));
        gradient33.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, -1));

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradient33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradient33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gradient32.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 480));

        appointmentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitalSuccessButton1.setText("Accept");
        gradient31.add(hospitalSuccessButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        hospitalEmergencyButton1.setText("Reject");
        gradient31.add(hospitalEmergencyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        hospitalPrimaryButton1.setText("Info");
        gradient31.add(hospitalPrimaryButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));
        gradient31.add(appointmentTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 480));

        appointmentpanel.add(gradient31, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 860, 480));

        gradient32.add(appointmentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 480));

        billpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout gradient38Layout = new javax.swing.GroupLayout(gradient38);
        gradient38.setLayout(gradient38Layout);
        gradient38Layout.setHorizontalGroup(
            gradient38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        gradient38Layout.setVerticalGroup(
            gradient38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        billpanel.add(gradient38, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 860, 480));

        gradient32.add(billpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 480));

        transactionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout gradient39Layout = new javax.swing.GroupLayout(gradient39);
        gradient39.setLayout(gradient39Layout);
        gradient39Layout.setHorizontalGroup(
            gradient39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        gradient39Layout.setVerticalGroup(
            gradient39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        transactionpanel.add(gradient39, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 860, 480));

        gradient32.add(transactionpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 480));

        namelabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        namelabel.setForeground(new java.awt.Color(44, 62, 80));
        namelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namelabel.setText("...");
        gradient32.add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 430, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("Welcome Back");
        gradient32.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(44, 62, 80));
        jLabel20.setText("Appointments:");
        gradient32.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        labelappointment.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelappointment.setForeground(new java.awt.Color(44, 62, 80));
        labelappointment.setText("0");
        gradient32.add(labelappointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 40, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(44, 62, 80));
        jLabel19.setText("Total Transactions:");
        gradient32.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, 30));

        labeltransactions.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labeltransactions.setForeground(new java.awt.Color(44, 62, 80));
        labeltransactions.setText("0");
        gradient32.add(labeltransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 40, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(44, 62, 80));
        jLabel21.setText("Pending Bills:");
        gradient32.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 20));

        labelbill.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelbill.setForeground(new java.awt.Color(44, 62, 80));
        labelbill.setText("0");
        gradient32.add(labelbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradient32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradient32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //labeltransactions.setText(String.valueOf(billTable.getApprovedTransactionCount()));
        //labelbill.setText(String.valueOf(billTable1.getPendingTransactionCount()));
        appointmentpanel.setVisible(false);
        billpanel.setVisible(false);
        transactionpanel.setVisible(false);
        loadAppointmentsFromDatabase();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void homesideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homesideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homesideMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        appointmentpanel.setVisible(true);
        billpanel.setVisible(false);
        transactionpanel.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void appointmentsideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentsideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentsideMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        appointmentpanel.setVisible(false);
        billpanel.setVisible(true);
        transactionpanel.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        appointmentpanel.setVisible(false);
        billpanel.setVisible(false);
        transactionpanel.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hospital.management.AppointmentTable appointmentTable1;
    private javax.swing.JPanel appointmentpanel;
    private javax.swing.JPanel appointmentside;
    private javax.swing.JPanel billpanel;
    private javax.swing.JPanel billside;
    private hospital.management.Gradient3 gradient31;
    private hospital.management.Gradient3 gradient32;
    private hospital.management.Gradient3 gradient33;
    private hospital.management.Gradient3 gradient34;
    private hospital.management.Gradient3 gradient35;
    private hospital.management.Gradient3 gradient36;
    private hospital.management.Gradient3 gradient37;
    private hospital.management.Gradient3 gradient38;
    private hospital.management.Gradient3 gradient39;
    private javax.swing.JPanel homeside;
    private hospital.management.HospitalEmergencyButton hospitalEmergencyButton1;
    private hospital.management.HospitalPrimaryButton hospitalPrimaryButton1;
    private hospital.management.HospitalSuccessButton hospitalSuccessButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelappointment;
    private javax.swing.JLabel labelbill;
    private javax.swing.JLabel labeltransactions;
    private javax.swing.JLabel namelabel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel transactionpanel;
    private javax.swing.JPanel transactionside;
    // End of variables declaration//GEN-END:variables
}
